### ISSUE TITLE
Can't use Distance type

### ISSUE THREAD

**Issue by avalsoff** [google/schema-dts#19]
<img width="731" alt="Screenshot 2019-05-17 at 14 59 20" src="https://user-images.githubusercontent.com/37933607/57926665-89a13280-78b4-11e9-9fc0-970c2fec374e.png">

**Comment by Eyas** [comment]
Thanks for the report.

Looks like fixing this needs a bit of a hack; the schema for "Distance" has no indication that it takes this form other than the text of the comment describing it (it's not represented as a data type, etc.). I think part of this is because, in JSON-LD, in theory, string is always a valid value. In practice, I don't know if this is always parsed correctly by crawlers.

For now, I think part of the fix is to get "Quantity" subclasses working right. But it's worth revisiting this and seeing if "string" should be a valid value for all nodes.

**Comment by Eyas** [comment]
Fixed in #21 and released as schema-dts 0.4.0
