### ISSUE TITLE
[Question] Plans for this library

### ISSUE THREAD

**Issue by ali-habibzadeh** [google/schema-dts#35]
Hi Guys,

I am considering this library as a base for creating a tool that takes string DOM and validates structured data.

I was just wondering, your library looks really good. How serious this library is? is this seen as a long term commitment?

**Comment by Eyas** [comment]
Hi Ali, yes-- the plan is to support this long term.

Note that this is an open-source project within Google that is supported long-term by its contributors, rather than a project officially supported by Google as a whole.

We maintain pretty much the same backwards compatibility guarantees as Schema.org's pending.schema.org schema (see #8).

**Comment by ali-habibzadeh** [comment]
That's great to hear @Eyas. Thanks for clarification
